- name: create a Docker Runtime environment

  hosts: all

  become: yes

  gather_facts: false

  tasks:

     - name: Remove if any existig old docker refernences

       package:

          name:

            - docker 

            - docker-clienr

            - docker-client-latest

            - docker-common

            - docker-latest

            - docker-latest-logrotate

            - docker-engine

          state: absent

       register: dockerremove

     - debug: 

        var: dockerremove.results
