- name: setup the docker repository && yum-utils && install docker
  hosts: master,worker
  become: yes
  gather_facts: no
  tasks:
    - name: install yum-utils
      package:
        name: 
          - yum-utils
        state: present
      tags: yumutils

    - name: add the repository
      shell: yum-config-manager \
             --add-repo \
             https://download.docker.com/linux/centos/docker-ce.repo
      args:
         creates: /etc/yum.repos.d/docker-ce.repo
      register: docker_repo_add
      tags: dockerrepo

    - local_action:
        module: copy
        content: "{{ docker_repo_add }}"
        dest: /home/kubeadmin/k8s/playbooks/{{inventory_hostname}}_docker_repo_add

    - name: install docker
      package:
        name:
         - containerd.io
         - docker-ce
         - docker-ce-cli
        state: present
        update_cache: true
        skip_broken: yes
      register: dockerinstall

    - debug:
        var: dockerinstall.results
    
    - local_action:
        module: copy
        content: "{{ dockerinstall }}"
        dest: /home/kubeadmin/k8s/playbooks/{{inventory_hostname}}_docker_repo_add

