- name: Final system pre-req's
  hosts: all
  become: yes
  tasks:
   - name: disable firewall service
     service:
        name: firewalld
        state: stopped
        enabled: false

   - name: Disable SWAP 
     shell: |
       swapoff -a

   - name: Disable SWAP in fstab 
     lineinfile:
       path: /etc/fstab
       regexp: 'swap'
       state: absent

   - name: disable SELinux
     command: setenforce 0
     ignore_errors: yes

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: Letting iptables see bridged traffic
     shell: cat <<EOF | sudo tee  /etc/sysctl.d/k8s.conf \
                      net.bridge.bridge-nf-call-ip6tables = 1 \
                      net.bridge.bridge-nf-call-iptables = 1 \
                      EOF

   - name: apply the iptables changes
     shell: sysctl --system

   - name: Add the Yum reposiory to Database
     yum_repository:  
        name: Kubernetes  
        description: K8s YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes  
        repo_gpgcheck: yes
        enabled: yes
     tags: k8repo
    
   - name: Reboot the targets after the swap and selinux 
     reboot: 
