- name: install K8s
  hosts: all
  become: yes
  tasks:
    - name: install the K8s pre-req
      shell: cat <<EOF |  tee getc/sysctl.d/k8s.conf \
                      net.bridge.bridge-nf-call-ip6tables = 1 \
                      net.bridge.bridge-nf-call-iptables = 1 \
                      EOF 
                      
    - name: apply the iptables changes 
      shell: sysctl --system
      
   # Ansible module usage
   # - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
   #   sysctl:
   #     name: net.bridge.bridge-nf-call-ip6tables
   #     value: 1
   #     state: present

   # - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
   #  sysctl:
   #    name: net.bridge.bridge-nf-call-iptables
   #    value: 1
   #    state: present
     
    - name: Add the Yum reposiory to Database
      yum_repository:  
        name: Kubernetes  
        description: K8s YUM repository
        baseurl: https:g/packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        gpgkey: https:g/packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes  
        repo_gpgcheck: yes
        enabled: yes
                
    - name: Set Selinux in permissive mode
      shell:  setenforce 0 
      
    - name: disbale selinux on reboot
      selinux:
        state: disabled
        
            
